### ISSUE TITLE
Crash when query first and undefined count

### ISSUE THREAD

**Issue by ptrushin** [SenyaMur/ag-grid-odata#10]
My case is:
1) Load first page from server, it did with $count (
https://github.com/SenyaMur/ag-grid-odata/blob/master/src/OdataProvider.ts#L946)
This step is ok
2) Load second page from server (after scrol grid), it did without $count
This step is ok
3) And after without scrol i do refresh (with aggrid purgeServerSideCache)
This step is crashed (near this line https://github.com/SenyaMur/ag-grid-odata/blob/master/src/OdataProvider.ts#L704)
I think it because of second page loaded firstly and without $count and  aggrid crashed.

I did workaround
new OdataProvider({
                callApi: options => {
                    if (!options.includes('$count=')) options = options + "&$count=true"
                   ...

But I think it is not good.

**Comment by SenyaMur** [comment]
Thank you.

I have to detect what was pressed purgeServerSideCache or first load for cancel all pending requests. 
I need take a time for investigate this situation.

**Comment by SenyaMur** [comment]
Please check new version [v1.0.11](https://www.npmjs.com/package/ag-grid-odata/v/1.0.11)
And give me feedback.

**Comment by SenyaMur** [comment]
Has this problem been solved?
