### ISSUE TITLE
Date filter not working

### ISSUE THREAD

**Issue by ptrushin** [SenyaMur/ag-grid-odata#11]
It serialize to odata like "1995-10-08 00:00:00T00:00:00.000Z", it is wrong format.

**Comment by SenyaMur** [comment]
Thanks for your issue
Can you show example how you do it?

**Comment by ptrushin** [comment]
https://codesandbox.io/s/hardcore-sea-oiz5b
try to change filter

**Comment by SenyaMur** [comment]
Thank you for your example. I checked new version [v1.0.12](https://www.npmjs.com/package/ag-grid-odata/v/1.0.12) on your example https://codesandbox.io/s/goofy-lichterman-o1mi4

**Comment by ptrushin** [comment]
It's ok when i choose from calendar.
But when I change date manual right in filter textbox i have an exeption.
Try to type 01 then 01 then 1999

**Comment by SenyaMur** [comment]
> Try to type 01 then 01 then 1999
It is not correct format date.
You must set correct date format. See more details https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Date_Time_String_Format

**Comment by ptrushin** [comment]
Hmm ... When I choose from calendar 01.01.1999 - it it ok, but when i type manually 01.01.1999 - it is not corrent format?
I don't think so.
I think it is because of when i type 199 in year part of filter it start to apply filter, but not wait when i finish type 1999.

**Comment by SenyaMur** [comment]
Did you change agDateColumnFilter to agTextColumnFilter for input to  textbox ?

**Comment by ptrushin** [comment]
i use you example https://codesandbox.io/s/goofy-lichterman-o1mi4 without any changes
browser - firefox

**Comment by ptrushin** [comment]
Wow, in chrome and yandex brower all is ok, problem only in firefox ...

**Comment by SenyaMur** [comment]
I reproduced the situation when inputting date in textbox in firefox browser. If date is incorrect return 'null'

**Comment by SenyaMur** [comment]
Please, check new version.

**Comment by ptrushin** [comment]
I cheked it, but it don't working good:
1) when i want to type in year 1990, i type 199, it runnung odata query with null, and after i finish 1990 and it running odata query again with good date. Row data in aggrid is flashing (empty and then good result) and i have one unnecessary query
2) and when i select in aggrid filter not Equals but something else like Greater then i have an odata error "The operator 'GreaterThan' is not supported for the 'null' literal; only equality checks are supported"

**Comment by SenyaMur** [comment]
It is specific of Firefox. You can check it in console `new Date('199-01-01 00:00:00')` 
In Firefox it will be **Invalid date**.
In Chrome and other cromium based browsers it will be parsed date.

What do you propose to do if the date is not correct **Invalid date** ?

**Comment by ptrushin** [comment]
I propose to do nothing when invalid date, not odata query, not aggrid refresh, nothing

**Comment by SenyaMur** [comment]
Done. You may check it on new version v1.0.15

**Comment by ptrushin** [comment]
Ok.
But if you can do nothing instead of query data without data filter (like now in 1.0.15), i think it wil be better.

**Comment by ptrushin** [comment]
Thanks.

**Comment by SenyaMur** [comment]
I can't do it. Because the package just translate ag-grid request to odata request per call.
