### ISSUE TITLE
Sorting does not work with groups (Server side)

### ISSUE THREAD

**Issue by AndrewZagovora** [SenyaMur/ag-grid-odata#12]
There is no parameter to sort the grouped columns.
I am using the Server Side mode.

Steps to replicate:
1. I am grouping the grid by some column 
2. I am changing the sorting of the group column by clicking on it.

Expected Result: get?$top=100&$apply=groupby((Column_Name)),aggregate($count%20as%20childCount))&$orderBy=childCount   
Actual Result:  get?$top=100&$apply=groupby((Column_Name)),aggregate($count%20as%20childCount))

**Comment by SenyaMur** [comment]
Thank you for your issue!
I fixed this in new version [v1.0.19](https://www.npmjs.com/package/ag-grid-odata/v/1.0.19)
After you check it, please write feedback.

**Comment by AndrewZagovora** [comment]
Working like a charm! Thank you, you can close the issue.
