### ISSUE TITLE
Pivot mode issue with latest ag-grid

### ISSUE THREAD

**Issue by pylnata** [SenyaMur/ag-grid-odata#15]
Hello Semen,
First of all - thank you for this library! Seems that it is the only one odata client for ag-grid. 
Recently after upgrade ag-grid to the latest version  I faced to the problem in pivot mode. Here is a fork: 
https://codesandbox.io/s/ag-grid-server-side-row-model-sample-forked-q9z15

Steps to reproduce:
1. Activate pivot mode
2. Move "Customer" to  Row groups, "Amount" to Values, "Order ID" to Column Labels.

The error appears:

Cannot read property 'blocks' of undefined
OdataProvider.eval
https://q9z15.csb.app/node_modules/ag-grid-odata/build/index.es.js:529:83
step
https://q9z15.csb.app/node_modules/ag-grid-odata/build/index.es.js:110:17

Could you please take a look?

**Comment by SenyaMur** [comment]
Thank you for issue.
I reproduced the issue. I'll try to fix.

**Comment by SenyaMur** [comment]
I fixed the issue in the [v1.0.20](https://www.npmjs.com/package/ag-grid-odata/v/1.0.20). 
Please, check it in your project and give me feedback.

**Comment by pylnata** [comment]
Hi, @SenyaMur I checked and this fix works! Thank you a lot!
