### ISSUE TITLE
Broken filtering with ag-grid@25

### ISSUE THREAD

**Issue by pylnata** [SenyaMur/ag-grid-odata#17]
Hello Semen,

I've just noticed one more critical thing that stopped to work in our project after upgrade of ag-grid.
It is filtering. No calls to API when change filtering settings. 

Here is fork for you with  customer field enabled to filter:

https://codesandbox.io/s/ag-grid-server-side-row-model-sample-forked-b0p8b

With ag-grid@25 and 1.0.20/1.0.19 ag-grid-odata  open Filters tab and try to filter Customers. No any call to API.

It to switch to ag-grid@24 -- all works - request to API is performed.

It would be great if you find time to fix this.

Thanks in advance.

**Comment by SenyaMur** [comment]
Hello, @pylnata. Just add `serverSideStoreType="partial"` to Grid options and filter will work.
For more see ag-grid [documentation](https://www.ag-grid.com/documentation/javascript/server-side-model-configuration/#custom-partial-store). 

P.S. Thank you for your issue. I added the option to my example.

**Comment by pylnata** [comment]
Thank you! I need "full" but I fould in docs that with serverSideFilteringAlwaysResets options it will force to make a call to api. And it works. You can close this issue.
