### ISSUE TITLE
Usage with TypeScript issue

### ISSUE THREAD

**Issue by kosmiq** [SenyaMur/ag-grid-odata#18]
First off, I can not thank you enough for creating and publishing this package. It just saved me a bunch of hours and implementation and testing. It seems to work really well, and was easy to implement and manages filter in a way that I do really appreciate and like as a baseline.

We are in a TypeScript (React) project, and using the examples as they are produces typescript errors:
![image](https://user-images.githubusercontent.com/322759/116548773-ffadd100-a8f4-11eb-9629-1cd3418b7d87.png)

I did not really look into the types, but it is solvable by doing typecasting as below:
![image](https://user-images.githubusercontent.com/322759/116547725-8feb1680-a8f3-11eb-8017-6581f8a08848.png)

Preferably the `OdataProvider` would export itself with a type corresponding to what is wanted by `setServerSideDatasource` in a typescript setup.

This is mostly to raise awareness of the issue and potentially help others that might hit the same snag.

**Comment by SenyaMur** [comment]
Thank you for your issue. I publish new version [1.0.22](https://www.npmjs.com/package/ag-grid-odata/v/1.0.22). Check it, please.

**Comment by kosmiq** [comment]
Hi, thanks for the super quick reply and publishing of a new version.

It did not fix things, unfortunately. It seems as if it only picks up the first defined getRows()
![image](https://user-images.githubusercontent.com/322759/116658616-84016200-a990-11eb-99bc-d3a6cab18eb6.png)

I think that the only safe solution to make AgGrids IServerSideDatasource AND IDatasource happy with the types is probably to export two functions, one for each datasource function and with separate types for the getRows function.

Something like
OdataProvider() // for IDataSource
OdataServerSideProvider // for IServerSideDatasource 

Both of those then share the same functions overall but when defining the getRows function they do export different typings.

Either that or attempt to use generics types and see if you can have some success with that.
https://www.typescriptlang.org/docs/handbook/2/generics.html

If you'd be willing to update the GitHub repo to the latest source I might take a crack at it when I have the opportunity.

**Comment by SenyaMur** [comment]
Thank you for your feedback. I publish new version [1.0.22](https://www.npmjs.com/package/ag-grid-odata/v/1.0.22), where I added new classes for implementation IDataSource and IServerSideDatasource. You can see it in example https://github.com/SenyaMur/ag-grid-odata/blob/master/examples/ag-grid-server-side-row-model-sample/src/index.tsx

**Comment by kosmiq** [comment]
Sorry I could not get back to you earlier.

I updated the package and removed the type casting. Then I got the below issue instead:
```
Argument of type 'OdataServerSideProvider' is not assignable to parameter of type 'IServerSideDatasource'.
  Types of property 'getRows' are incompatible.
    Type '(params: import("[path]/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iServerSideDatasource").IServerSideGetRowsParams) => void' is not assignable to type '(params: import("[path]/node_modules/ag-grid-community/dist/lib/interfaces/iServerSideDatasource").IServerSideGetRowsParams) => void'.
      Types of parameters 'params' and 'params' are incompatible.
        Type 'import("[path]/node_modules/ag-grid-community/dist/lib/interfaces/iServerSideDatasource").IServerSideGetRowsParams' is not assignable to type 'import("[path]/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iServerSideDatasource").IServerSideGetRowsParams'.
          Types of property 'parentNode' are incompatible.
            Type 'import("[path]/node_modules/ag-grid-community/dist/lib/entities/rowNode").RowNode' is not assignable to type 'import("[path]/node_modules/@ag-grid-community/core/dist/cjs/entities/rowNode").RowNode'.
              Types have separate declarations of a private property 'mainEventService'.ts(2345)
```

But then I started digging and noticed that you import
```
"@ag-grid-community/all-modules": "^25.1.0",
"@ag-grid-enterprise/all-modules": "25.1.0"
```
in your package.json and that I use
```
"ag-grid-community": "^25.1.0",
"ag-grid-enterprise": "^25.1.0",
```

and for some reason they do not seem to be the same. Then I made an attempt to transition to their module system as well and hit all kinds of type errors in their event declarations.
```
AgGridReact', gave the following error.
    Type '(event: import("[path]/node_modules/@ag-grid-community/all-modules/node_modules/@ag-grid-community/core/dist/cjs/events").SelectionChangedEvent) => void' is not assignable to type '(event: import("[path]/node_modules/@ag-grid-community/core/dist/cjs/events").SelectionChangedEvent) => void'.
      Types of parameters 'event' and 'event' are incompatible.
        Type 'import("[path]/node_modules/@ag-grid-community/core/dist/cjs/events").SelectionChangedEvent' is not assignable to type 'import("[path]/node_modules/@ag-grid-community/all-modules/node_modules/@ag-grid-community/core/dist/cjs/events").SelectionChangedEvent'.
```

But on the positive side, the error related to your function disappeared :)

So from now on, I think we can assume that this is an issue caused by ag-grid and their modules export.

**Comment by SenyaMur** [comment]
What else can I do for you ?

**Comment by kosmiq** [comment]
All your help is very appreciated. I will close this issue since the problem lies not in your packgage but rather in the types (or different types between packages) from Ag-Grid as I see it.
