### ISSUE TITLE
AND/OR filters don't work

### ISSUE THREAD

**Issue by kasparkallas** [SenyaMur/ag-grid-odata#2]
Hi! @SenyaMur

Thank you for this great little package! It seems to work like magic in combination with ASP.NET and Entity Framework.

I found a bug though. You can quickly repro it with the demo by adding `filter="agNumberColumnFilter"` to Price and filtering it with AND/OR (for example less than 200 and greater than 50).

The error is:
```
TypeError
me.odataOperator[col.type] is not a function
```
and also:
```
ReferenceError
keyEventHandler is not defined
```

**Comment by SenyaMur** [comment]
Hi @kasparkallas!

Thank you for your bug report. I will soon fix it.
