### ISSUE TITLE
Queries with null as value

### ISSUE THREAD

**Issue by kosmiq** [SenyaMur/ag-grid-odata#23]
Hello again,

So I've hit another issue that I'd like to discuss.

- I have column that is typed as NVARCHAR, null in the SQL database
- I set the column as set filter type in ag grid and supply it with unique values from the database (A, B, C, D, E, null)
- In Ag-Grid they show up just fine in the filter for the column like so:
  - (Select All)
  - (Blanks) [this is the one that is null]
  - C
  - D
  - E
  - K
- I can filter just fine on anything that is an actual value or if I use (Select All).

The ODATA query URL then looks like this:
`$filter=tolower(ColumnName)%20in%20(%27c%27,%27d%27,%27e%27,%27k%27)` 
(unencoded: `$filter=tolower(ColumnName) in ('c','d','e','k')`)
and results are returned as expected.

Using the (Blanks) value however, where the value actually is NULL will give 0 results. This is because the query looks like this: 
`$filter=tolower(GearboxCode)%20in%20(%27null%27)`
(unencoded: `$filter=tolower(GearboxCode) in ('null')`)
but would need to look like this:
`$filter=tolower(GearboxCode)%20in%20(null)`
(unencoded: `$filter=tolower(GearboxCode) in (null)`)
(note the lack of '' [encoded as %27] around the null value).

Is there an easy way to solve this and have the query work as I'd need above?

**Comment by SenyaMur** [comment]
Hi, @kosmiq 
First of all, thank you for your issue.

For begin you can customize your filter. Add several property for pretty view:
```js
filterParams: {
        defaultToNothingSelected: true,
        suppressSelectAll: true,
        suppressMiniFilter: true
}
```

At first glance, it is difficult to say what can be offered here.
What can do you offer?

**Comment by kosmiq** [comment]
Hi and thanks for the quick replies as always. 

In this particular case the solution is (?) something like being able to send null as a real odata null and not the string null.

Perhaps something similar to the enums solution previously added on my request. I imagine something like "true null columns" where any added column key will send null as null and not as 'null'.

**Comment by SenyaMur** [comment]
Perhaps, is need to add ability for set filters interpret values as is without converts or may be add ability for custom builder of filer for the column.

**Comment by kosmiq** [comment]
> Perhaps, is need to add ability for set filters interpret values as is without converts or may be add ability for custom builder of filer for the column.

Using values as is sounds like good idea. I think that would indeed solve my issue.

**Comment by SenyaMur** [comment]
In this case I must to know what exactly put to query string.  String or null or number, because for string value need to add quotes.
I can try to detect what kind of value and use it for set filter

**Comment by kosmiq** [comment]
Should it be detected, or rather keep the current behavior as default and offer a setting similar to caseSensitiveColumns where you can define columns and their type for the specific cases where it is needed?

How do you imagine detecting types?

I have feeling that detecting things could end up breaking queries, like sometimes people do store numbers as strings in the database and might want to use 0 as "0" when performing ODATA queries.

Perhaps something like (very theoretical) would be a solution for users with this specific need?
```
columnDataTypes: [
    {
        column: 'columnA',
        dataType: 'number', // will interpret all values as numbers and use them as such
        trueNull: true, // will send null as null
    },
    {
        column: 'columnB',
        dataType: 'string', // will interpret all values as strings and use them as such
        trueNull: false, // will send null as 'null'
    },
]
```

**Comment by SenyaMur** [comment]
I think to try to define a value like typeof and depending on the value choose a way to add the value to the query string

**Comment by SenyaMur** [comment]
Hi, @kosmiq! I added new property for implement custom filter for specific column in new [v1.0.25](https://www.npmjs.com/package/ag-grid-odata/v/1.0.25)
See example https://github.com/SenyaMur/ag-grid-odata/blob/master/examples/ag-grid-server-side-row-model-sample/src/index.tsx#L31

**Comment by kosmiq** [comment]
Thank you very much! I'm going to look into it and try it out as soon as I can.

**Comment by kosmiq** [comment]
So I've tested this and it mostly works great but with some caveats.

I created a customFilter like this (note that `StringColumn` is not the real name of the column of course)
```
StringColumn: (colName, col, isCaseSensitive, provider) => {
    debugger;
    type ColTypes = keyof typeof provider.odataOperator; // just a fix for getting the type and key of the odataOperator and being able to use it in the TypeScript environment as index for odataOperator below
    const colType: ColTypes = col.type;
    return provider.odataOperator[colType](colName, col.filter, false);
},
```

This constructs an odata query looking like this:
`https://[backendAddress]/odata/[EndPoint]?$count=true&$top=1000&$filter=contains(tolower(StringColumn),h46h)`

Note that the h46h is not wrapped in '' which it should be since its a contains query. The correct query string would look like this:
`https://[backendAddress]/odata/[EndPoint]?$count=true&$top=1000&$filter=contains(tolower(StringColumn),'h46h')` (note 'h46h'), without '' around the value the backend returns http 400 bad request.

And from what I can see I am using the oDataOperator like it is used in the original implementation. And in the original implementation h46h is indeed wrapped in ''.

Am I missing something here? :(

**Comment by SenyaMur** [comment]
Hi, @kosmiq! 
The **contains** operator using for string. For your case you need manual add quotes for filter value.

```js
return provider.odataOperator[colType](colName, `'${col.filter}'`, false);
 ```

This behaivour is default for text column see in https://github.com/SenyaMur/ag-grid-odata/blob/master/src/OdataProvider.ts#L454

What do you want to do exactly ? Why you use custom filter in this case ?

**Comment by kosmiq** [comment]
> Hi, @kosmiq!
> The **contains** operator using for string. For your case you need manual add quotes for filter value.
> 
> ```js
> return provider.odataOperator[colType](colName, `'${col.filter}'`, false);
> ```
> 
> This behaivour is default for text column see in https://github.com/SenyaMur/ag-grid-odata/blob/master/src/OdataProvider.ts#L454
> 
> What do you want to do exactly ? Why you use custom filter in this case ?

I looked at the wrong part of the code, good to know that it is added that way in the original implementation as well.
I just used it as an example, because I noticed that '' was not added by another custom filter I created, so I just attempted to create the most basic baseline. So that custom filter will not be used, it was just for testing and I thought I found a bug.

But then all is good, thanks again for feedback and quick fixes!
