### ISSUE TITLE
Proposed code improvements of the library

### ISSUE THREAD

**Issue by kosmiq** [SenyaMur/ag-grid-odata#24]
Hi,

While looking at the code I took some notes that I thought I'd add as proposed improvements. They are not at all related to functionality (still working great!), but rather to ease development and reading for users of the package.

-  OdataProvider.ts contains a comment in russian (?) on line 798. Could this be updated to be in english, like the other comments in the code?
- Could smaller functions be separated into their own files and imported, to keep the length of the OdataProvider.ts shorter?
  - escapeRegExp
  - replaceAll
- Could interfaces and classes be separated into their own files as well?

I might do a PR if I have the time and get around to it. :)

Edit: I forked and created a branch here: https://github.com/kosmiq/ag-grid-odata/tree/split-into-modules. It's just a proposal, so I'll let you decide what to do with it. :)

**Comment by SenyaMur** [comment]
Hi, @kosmiq 
Thank you for your work. I need to take a time for analyze your modifications.

**Comment by kosmiq** [comment]
A followup question here. I noticed that you are using rollup, is that needed for a specific reason? I think the package could be compiled using only TypeScript compile (tsc) as long as the tsconfig is up to date.

But I could be missing something related to using rollup on the other hand?

**Comment by SenyaMur** [comment]
I use rollup when the library was not on typescript. Perhaps, now it is unnecessary.

**Comment by SenyaMur** [comment]
Separate classes is Ok. 
Separate types is not necessary, because all types is small 
Separate functions in lot of files not good idea. Better, make file utils.ts for all support of functions

**Comment by SenyaMur** [comment]
Hi, @kosmiq 
>OdataProvider.ts contains a comment in russian (?) on line 798. Could this be updated to be in english, like the other comments in the code?

Translated

>Could smaller functions be separated into their own files and imported, to keep the length of the OdataProvider.ts shorter?
escapeRegExp
replaceAll

Move to utils.ts

>Could interfaces and classes be separated into their own files as well?

It is unnecessary, because all interfaces are small

Rollup was deleted

I didn't separate classes to different files, because both classes linked each over. It is not good for compile.

Thank you for your suggestions!

**Comment by kosmiq** [comment]
Great! Happy I could be of some help, and you do own the lib so I am satisfied with whatever you decide. :)
