### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by goleafs** [SenyaMur/ag-grid-odata#26]
Demo link seems to crash transpiling.
Also, any chance there is an angular sample?

**Comment by SenyaMur** [comment]
Hi, @goleafs ! What link you try open?
Currently, i don't know angular, but I'll try create sample.

**Comment by SenyaMur** [comment]
I created sample on angular for you https://codesandbox.io/s/ag-grid-odata-angular-ls3lj?file=/src/app/app.component.ts

**Comment by goleafs** [comment]
Hey, I tried the one on main page.
Thank you for the angular sample!! Seems to work... I will check it out closer now.
FYI it looks like endpoints are being called twice on the demo (can reproduce clicking column header).
![image](https://user-images.githubusercontent.com/5503729/123845726-8590cd00-d8e2-11eb-910e-2b7a31ad6ea3.png)

**Comment by SenyaMur** [comment]
It is correct, because browser send OPTIONS request and then GET  request.
