### ISSUE TITLE
please publish type definition @types/ag-grid-odata

### ISSUE THREAD

**Issue by harishrathi** [SenyaMur/ag-grid-odata#3]

**Comment by SenyaMur** [comment]
Ok. I'll do it soon.

**Comment by SenyaMur** [comment]
Hi, I added type definition, please check my commit (9ed37746c374cbe87f52c132c62ef4f439fa01f6). If all is ok, then I'll publish to npm new version

**Comment by harishrathi** [comment]
Thanks a lot for adding type definitions. I am using it for angular thought. The peer dependency of `react` is something not clear to me. As I understand the type definition should depend only on `ag-grid`.

Also it would be great, if you can expose a function which takes the `IServerSideGetRowsParams` and return the `OData` filter.

**Comment by SenyaMur** [comment]
Hi, I remove react from dependencies and add function **getOdataQuery** which takes the IServerSideGetRowsParams or IGetRowsParams and return odata query  without base url. Please check commit(a32e0ae12e6eda9c73955ba81ab19ad8c003a664) and give me feedback.

**Comment by harishrathi** [comment]
It looks great, thanks a lot for making changes. Can you please publish it asap?

**Comment by SenyaMur** [comment]
Sorry for delay. 
I found out, that I don't know how to publish typescript types with JavaScript code.
I think that I have to rewrite all code on typescript for publish what you need. 
I'll try to do it soon. If you know how to publish type define types for this project you may create pull request.

**Comment by SenyaMur** [comment]
Hi, I convert project to typescript and publish new version [1.0.7](https://www.npmjs.com/package/ag-grid-odata/v/1.0.7).
