### ISSUE TITLE
There is an error with your odata provider

### ISSUE THREAD

**Issue by saeidi-dev** [SenyaMur/ag-grid-odata#30]
Hi there is this error
`
ERROR TypeError: Cannot read properties of undefined (reading 'setSecondaryColumns')
    at OdataProvider.getRows (OdataProvider.js:720)
`
Angular Version 13
ag-grid version is 26.2.0

Thanks

**Comment by SenyaMur** [comment]
Hi, @saeidi-dev . Can you show me an example of this situation?

**Comment by saeidi-dev** [comment]
`
onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    this.gridApi.sizeColumnsToFit();

    this.gridApi.setServerSideDatasource(
      new OdataProvider({
        callApi: (options) => fetch(`https://example.com/api${options}`)
          .then((resp) => resp.json())
          .then(resp => {
            return resp.value;
          }),
        beforeRequest: (query, provider) => {
          console.warn(query, provider);
          // query.expand = ['customer'];
        },
        afterLoadData: (options, rowData, totalCount) => {
          console.log(rowData, totalCount);
          if (options.skip === 0 && rowData.length > 0) {
            params.columnController.autoSizeAllColumns();
          }
        }
      })
    );
  }
`

**Comment by SenyaMur** [comment]
setSecondaryColumns is use in pivot mode. See ag-grid documentation:
https://www.ag-grid.com/javascript-data-grid/server-side-model-pivoting/

**Comment by SenyaMur** [comment]
Can you test your example on 25 version ag-grid? This situation is the same?

**Comment by saeidi-dev** [comment]
In any case, this problem was not solved. If you can, try this on version 26.2.0, because I made the changes too, but the problem is not resolved.

**Comment by SenyaMur** [comment]
Hi, @saeidi-dev. Than you for your issue. I fixed it in new version [ag-grid-odata v1.0.29](https://www.npmjs.com/package/ag-grid-odata/v/1.0.29).

**Comment by saeidi-dev** [comment]
> Hi, @saeidi-dev. Than you for your issue. I fixed it in new version [ag-grid-odata v1.0.29](https://www.npmjs.com/package/ag-grid-odata/v/1.0.29).

thanks 👌
