### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by saeidi-dev** [SenyaMur/ag-grid-odata#35]
Hello my friend
There is a dependency problem in your package, please check and fix this

Could not resolve dependency:
npm ERR! peer ag-grid-community@"^26.2.1" from ag-grid-odata@1.0.29
npm ERR! node_modules/ag-grid-odata
npm ERR!   ag-grid-odata@"^1.0.29" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ag-grid-community@26.2.1
npm ERR! node_modules/ag-grid-community
npm ERR!   peer ag-grid-community@"^26.2.1" from ag-grid-odata@1.0.29
npm ERR!   node_modules/ag-grid-odata
npm ERR!     ag-grid-odata@"^1.0.29" from the root project

**Comment by SenyaMur** [comment]
Hellow, @saeidi-dev. You have to install to your project package ag-grid-community of version 26.2.1 or later

**Comment by saeidi-dev** [comment]
I use these versions
"ag-grid-angular": "^ 27.2.1",
"ag-grid-community": "^ 27.2.1",
"ag-grid-enterprise": "^ 27.2.1",
"ag-grid-odata": "^ 1.0.29",

**Comment by saeidi-dev** [comment]
> Hellow, @saeidi-dev. You have to install to your project package ag-grid-community of version 26.2.1 or later

I use these versions
"ag-grid-angular": "^ 27.2.1",
"ag-grid-community": "^ 27.2.1",
"ag-grid-enterprise": "^ 27.2.1",
"ag-grid-odata": "^ 1.0.29",

**Comment by ali-memar** [comment]
> > Hellow, @saeidi-dev. You have to install to your project package ag-grid-community of version 26.2.1 or later
> 
> I use these versions "ag-grid-angular": "^ 27.2.1", "ag-grid-community": "^ 27.2.1", "ag-grid-enterprise": "^ 27.2.1", "ag-grid-odata": "^ 1.0.29",
> 
> error (when npm install): code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: ag-grid-odata@1.0.29 npm ERR! Found: ag-grid-community@27.2.1 npm ERR! node_modules/ag-grid-community npm ERR! ag-grid-community@"^27.2.1" from the root project npm ERR! peer ag-grid-community@"~27.2.0" from ag-grid-angular@27.2.1 npm ERR! node_modules/ag-grid-angular npm ERR! ag-grid-angular@"^27.2.1" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer ag-grid-community@"^26.2.1" from ag-grid-odata@1.0.29 npm ERR! node_modules/ag-grid-odata npm ERR! ag-grid-odata@"^1.0.29" from the root project npm ERR! npm ERR! Conflicting peer dependency: ag-grid-community@26.2.1 npm ERR! node_modules/ag-grid-community npm ERR! peer ag-grid-community@"^26.2.1" from ag-grid-odata@1.0.29 npm ERR! node_modules/ag-grid-odata npm ERR! ag-grid-odata@"^1.0.29" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I also have this problem, please check

**Comment by SenyaMur** [comment]
Hi. friends. I publish new version [v1.0.30](https://www.npmjs.com/package/ag-grid-odata/v/1.0.30). Please check it and give me feedback.

**Comment by saeidi-dev** [comment]
Thanks
