### ISSUE TITLE
AG Grid 28.0.x

### ISSUE THREAD

**Issue by saeidi-dev** [SenyaMur/ag-grid-odata#39]
Hi my friend
In the new ag-grid update, a number of methods have been renamed. Thank you for checking.

WARNING:
=> AG Grid: since version 28.0.x setSecondaryColumns has been renamed, please use setPivotResultColumns instead

[AG Grid Changelog](https://www.ag-grid.com/changelog/?fixVersion=28.0.0)

**Comment by SenyaMur** [comment]
Hi, @saeidi-dev. Thank you for your issue.
I publish new version [v1.0.31](https://www.npmjs.com/package/ag-grid-odata/v/1.0.31) with support ag-grid v28. 
Check the new version and send me feedback.

**Comment by saeidi-dev** [comment]
thank you ;)

**Comment by dvlyon** [comment]
@SenyaMur now I am gettting this error, had to rollback to 1.0.30.

`Uncaught TypeError: Cannot read properties of undefined (reading 'setPivotResultColumns')
    at ColumnApi.setSecondaryColumns (ag-grid-community.auto.esm.js:44265:1)
    at OdataProvider.getRows (OdataProvider.ts:830:1)
    at ag-grid-enterprise.auto.esm.js:45904:1`

Using

`"ag-grid-community": "28.1.1",
        "ag-grid-enterprise": "28.1.1",
        "ag-grid-odata": "1.0.30",
        "ag-grid-react": "28.1.1",`

**Comment by saeidi-dev** [comment]
Error: TypeError: Cannot read properties of undefined (reading 'setPivotResultColumns')

**Comment by SenyaMur** [comment]
Hi, @saeidi-dev. Thank you for your feedback.
I publish new version [v1.0.32](https://www.npmjs.com/package/ag-grid-odata/v/1.0.32) with fix this error.
