### ISSUE TITLE
Server Side Pagaination

### ISSUE THREAD

**Issue by eswwaa** [SenyaMur/ag-grid-odata#46]
Hi SenyaMur,
  I've been using your OData plugin for ag-grid for a small 4 row table, which is great . I am having an issue with server side pagination (aka, loads each page from an api call when clicking on a new page) and was wondering what I'm doing incorrectly.  Given below...

  onGridReady(params: GridReadyEvent) {
    params.api.setServerSideDatasource(
      new OdataServerSideProvider({
        callApi: (options) =>
          axiosApp
            .get(`/odata/v1/Data${options}`)
            .then((resp) => {
              return resp.data;
            }),
        beforeRequest: (
          query: OdataQueryOptions,
          provider: OdataProvider,
          request: IGetRowsParams | IServerSideGetRowsRequest
        ) => {
          query.select = new Array<string>();
          this.state.columnDefs.forEach((column, index) => {
            query.select?.push(column.field);
          });

          // NOTE: I do this to get any pagination going otherwise all the items are returned
          request.startRow = params.api.paginationGetCurrentPage();
          request.endRow = params.api.paginationGetPageSize();
        },
        afterLoadData: (options, rowData, totalCount) => {    // NOTE: totalCount is correct at 6
          if (options.skip === 0 && rowData.length > 0) {
            params.api.sizeColumnsToFit();
          }
        },
      })
    );
  }

<div style={this.state.style} className="ag-theme-bootstrap">
  <AgGridReact
    rowModelType="serverSide"
    cacheBlockSize={4}
    pagination={true}
    paginationPageSize={4}
    columnDefs={this.state.columnDefs}
    onGridReady={this.onGridReady.bind(this)}
    defaultColDef={{
      sortable: true,
      resizable: true,
      filterParams: {
        newRowsAction: "keep",
        browserDatePicker: true,
      },
    }}
  />

I get below in return which is correct from the backend but the total count for the pagination is 4 in the table and I can't get to the next two items.  In afterLoadData totalCount is correct at 6. Also (see NOTE) the only way I can get pagination in the url is to do the below by hand.  Does the plugin support server side pagination (if I return everything the pagination is fine)?

// See Note: above
          request.startRow = params.api.paginationGetCurrentPage();
          request.endRow = params.api.paginationGetPageSize();

{
  "@odata.context": "https://localhost:5001/odata/v1/$metadata#Data(Name,Description,TimeFrame,Id)",
  "@odata.count": 6,
  "value": [
    {
      "Name": "Name1",
    },
    {
      "Name": "Name2",
    },
    {
      "Name": "Name3",
    },
    {
      "Name": "Name4",
    }
  ]
}

**Comment by SenyaMur** [comment]
Hi, @eswwaa 

Can you show first request url which create  OdataServerSideProvider. And what return response body.

**Comment by eswwaa** [comment]
Hi SenyaMur,
   Thanks for getting back to me.  If I do not manually add the startRow/endRow parameters to the url I get
https://localhost:5001/odata/v1/data?$select=Name,Description,TimeFrame,Id
{
  "@odata.context": "https://localhost:5001/odata/v1/$metadata#DreamVacation(Name,Description,TimeFrame,Id)",
  "value": [
    {"Name": "Item1",},
    {"Name": "Item2",},
    {"Name": "Item3",},
    {"Name": "Item4",},
    {"Name": "Item5",},
    {"Name": "Item6",}
  ]
}
otherwise I get
https://localhost:5001/odata/v1/data?$count=true&$top=4&$select=Name,Description,TimeFrame,Id

{
  "@odata.context": "https://localhost:5001/odata/v1/$metadata#DreamVacation(Name,Description,TimeFrame,Id)",
  "@odata.count": 6,
  "value": [
    {"Name": "Item1"},
    {"Name": "Item2"},
    {"Name": "Item3"},
    {"Name": "Item4"}
]}

when I add below
          request.startRow = params.api.paginationGetCurrentPage();
          request.endRow = params.api.paginationGetPageSize();

Note: I did remove some fields to make this smaller.
Thanks for any help

**Comment by SenyaMur** [comment]
Hi, @eswwaa. You should set next grid options:
          pagination={true}
          paginationPageSize={10}
          cacheBlockSize={10}

More information see https://www.ag-grid.com/javascript-data-grid/server-side-model-pagination/

**Comment by eswwaa** [comment]
Hi SenyaMur,
   I tried your suggestion and nothing changed, the skip and top variables are not populated so the entire result set is returned.  As long as those numbers are set the values shouldn't matter as they indicate the size of the result set page, I had them at 4 before (due to a small table) which should work perfectly fine it's just that skip and top are never set.

**Comment by eswwaa** [comment]
Regrettably my project is way too big to distill down.  If you take this onGridReady() and insert it into any paginated grid and set a breakpoint in beforeRequest you'll see request.startRow/endRow are undefined.  If you define them doing as seen below it'll request it correctly but the total size is not set correctly.


  onGridReady(params: GridReadyEvent) {
    params.api.setServerSideDatasource(

      new OdataServerSideProvider({
        callApi: (options) =>
          axiosApp
            .get(`/odata/v1/dreamVacation${options}`)
            .then((resp) => {
              console.log(resp.data);
              return resp.data;
            }),
        beforeRequest: (
          query: OdataQueryOptions,
          provider: OdataProvider,
          request: IGetRowsParams | IServerSideGetRowsRequest
        ) => {
          //query.expand = ["customer"];
          query.select = new Array<string>();
          this.state.columnDefs.forEach((column, index) => {
            query.select?.push(column.field);
          });
          
          // To force paging
          //request.startRow = params.api.paginationGetCurrentPage();
          //request.endRow = params.api.paginationGetPageSize();
        },
        afterLoadData: (options, rowData, totalCount) => {
          if (options.skip === 0 && rowData.length > 0) {
            params.api.sizeColumnsToFit();
            params.api.columnController.autoSizeAllColumns();
          }
        },
      })
    );
  }

I'm going to try and see how I can fix it myself if you have any suggestions let me know.

**Comment by SenyaMur** [comment]
I ask you your grid options. Not a data provider.  For example: pagination, paginationPageSize etc.
I test your case in ag-grid v28. Which version you use?

**Comment by eswwaa** [comment]
<div style={this.state.style} className="ag-theme-bootstrap">
              <AgGridReact
                rowModelType="serverSide"
                cacheBlockSize={10}
                pagination={true}
                paginationPageSize={10}
                columnDefs={this.state.columnDefs}
                onGridReady={this.onGridReady.bind(this)}
                defaultColDef={{
                  sortable: true,
                  resizable: true,
                  filterParams: {
                    newRowsAction: "keep",
                    browserDatePicker: true,
                  },
                }}
              />

  createColumnDefs(): Array<IColumnDefinitions> {
    var columns: Array<IColumnDefinitions> = [];

    columns.push({ field: "Name", headerName:"Name", sortable: true, filter: true, width: 140 });
    columns.push({ field: "Description", headerName:"Description", sortable: true, filter: true, width: 210 });
    columns.push({ field: "TimeFrame", headerName:"Time Frame", sortable: true, filter: true, width: 190 });
    columns.push({ field: "Id", headerName:"", sortable: false, filter: true, width: 65, cellRenderer: this.RenderOptions });

    return columns;
}

I'm using ag-grid v28 as well.

**Comment by SenyaMur** [comment]
You need add `serverSideStoreType="partial"`
See my example https://codesandbox.io/s/ag-grid-server-side-row-model-sample-paging-ggvil8?file=/src/index.js

**Comment by eswwaa** [comment]
That worked, thanks so much, this plugin is really great!

**Comment by SenyaMur** [comment]
You are welcome.
