### ISSUE TITLE
Wrong Request if using Browser Picker in Ag-grid

### ISSUE THREAD

**Issue by AlexLDP** [SenyaMur/ag-grid-odata#5]
if select date from ag grid picker(browser picker), this library adds  orphan time

AR: $filter: StartDate eq 2020-07-15 00:00:00T00:00:00.000Z
ER: $filter: StartDate eq 2020-07-15T00:00:00.000Z

index.es.js=>184 Line of Code. Can it somehow configured? No special settings of Ag Grid

**Comment by SenyaMur** [comment]
How you resolve this issue ?

**Comment by AlexLDP** [comment]
Thanks for asking. In this particular case I just changed result options before request is send. I do not why it was happened. But as I understand it look that from ag grid value comes in this format 12/12/2020 00:00:00

**Comment by SenyaMur** [comment]
Which browser you use?
By default date filter not contain time just. date. May be different behaviour when use browser date picker  or ag-grid date picker?

**Comment by SenyaMur** [comment]
Can you show repository with example?

**Comment by AlexLDP** [comment]
Unfortunately I cannot show. But it is simple grid setting with everything stock. With newest chrome browser. Any way it is fixed.
