### ISSUE TITLE
Sample data not working in demo anymore

### ISSUE THREAD

**Issue by au5ton** [SenyaMur/ag-grid-odata#50]
The demo linked in the description doesn't work anymore: https://codesandbox.io/s/ag-grid-server-side-row-model-sample-zqujt?fontsize=14&hidenavigation=1&theme=dark

It references this Heroku app that has since been removed or disabled: https://odatav4sample.herokuapp.com/odata/$metadata

**Comment by SenyaMur** [comment]
Hi, @au5ton. Unfortunately, I can't restore it project. If you need, I can create new example.
For example with it endpoint https://services.odata.org/V4/Northwind/Northwind.svc/Order_Details_Extendeds?$top=100
