### ISSUE TITLE
Pagination Issue 

### ISSUE THREAD

**Issue by farrukhazeem** [SenyaMur/ag-grid-odata#6]
There is no clue for handling pagination in ag-grid on serverside. When the row data is less than the expected paginationPageSize, the next button should be disabled because there is no more data.

For example the paginationPageSize = 10 and the rowData.length = 3. The pagination should be stopped.

**Comment by SenyaMur** [comment]
Thanks for your question. 
Which mode do you use: server mode or client?
Can you show ag-grid settings which you set for this situation?

**Comment by SenyaMur** [comment]
Set cacheBlockSize = 10, may be this help you.
In this demo is show pagination correct work
https://codesandbox.io/s/ag-grid-server-side-row-model-sample-jel5e?file=/src/index.js

**Comment by farrukhazeem** [comment]
This is my ag-grid settings 

<AgGridReact
          modules={AllModules}
          sideBar='filters'
          floatingFilter
          //Enable server mode DataSource
          rowModelType="serverSide"
          // fetch 100 rows per at a time
          cacheBlockSize={10}
          pagination={true}
          paginationPageSize={10}

          // rowHeight={60}
          // headerHeight={60}
          // floatingFiltersHeight={50}
          onGridReady={onGridReady}
          // getChildCount={data => {
          //   return data && data.childCount;
          // }}
          
          defaultColDef={{
            sortable: true,
            resizable: true,
            filter: true,
            // enablePivot: true,
            // allowedAggFuncs: ["sum", "min", "max", "avg", "count"],
            
            filterParams: {
              newRowsAction: "keep",
              // browserDatePicker: true
            }
          }}
        >
          {/* enableRowGroup */}
          <AgGridColumn
                field="item_id"
                headerName="Transaction Reference Number"
                enableValue
                minWidth={180}
                filter="agNumberColumnFilter"

**Comment by farrukhazeem** [comment]
<AgGridReact
          modules={AllModules}
          sideBar='filters'
          floatingFilter
          //Enable server mode DataSource
          rowModelType="serverSide"
          // fetch 100 rows per at a time
          cacheBlockSize={10}
          pagination={true}
          paginationPageSize={10}

          // rowHeight={60}
          // headerHeight={60}
          // floatingFiltersHeight={50}
          onGridReady={onGridReady}
          // getChildCount={data => {
          //   return data && data.childCount;
          // }}
          
          defaultColDef={{
            sortable: true,
            resizable: true,
            filter: true,
            // enablePivot: true,
            // allowedAggFuncs: ["sum", "min", "max", "avg", "count"],
            
            filterParams: {
              newRowsAction: "keep",
              // browserDatePicker: true
            }
          }}
        >
          {/* enableRowGroup */}
          <AgGridColumn
                field="item_id"
                headerName="Transaction Reference Number"
                enableValue
                minWidth={180}
                filter="agNumberColumnFilter"

**Comment by farrukhazeem** [comment]
![p1](https://user-images.githubusercontent.com/26819319/89280236-c4ca8580-d661-11ea-8993-f66c84a70188.png)

It is repeating onwards when clicking next page.

**Comment by SenyaMur** [comment]
Is contained In your first response of odata @odata.count field where request contain $count=true?
Like below 
Request: https://odatav4sample.herokuapp.com/odata/Orders?$count=true&$top=10&$expand=customer
Answer: 
```json
{"@odata.context":"http://odatav4sample.herokuapp.com/odata/$metadata#Orders(Customer())",
"@odata.count":108,
"value":[
{"Id":1,"Title":"ijk22","Price":286.0,"Amount":594.0,"Created":"2020-08-23T00:00:00Z","Customer":{"Id":3,"Name":"Peter"}},

{"Id":10,"Title":"ijk13","Price":169.0,"Amount":351.0,"Created":"2020-08-14T00:00:00Z","Customer":{"Id":3,"Name":"Peter"}}
]}
```

**Comment by farrukhazeem** [comment]
thanks for your guidance

**Comment by SenyaMur** [comment]
Is it solution helped you to resolve this issue?
