### ISSUE TITLE
Grouping issue

### ISSUE THREAD

**Issue by AndrewZagovora** [SenyaMur/ag-grid-odata#7]
The issue is related to object we work with if we receive more rows than we expect to get:
https://github.com/SenyaMur/ag-grid-odata/blob/fb165f930bca8759e296c33214b82974d9ce1266/build/index.js#L497-L500

To fix it, the code in line 498 should be the following:
`count_1 = y.value[0].count;`

Please can you check the issue on your side and fix it.
Regards and thank you.

**Comment by SenyaMur** [comment]
Thanks for you issue. I fixed this bug. Check it new version [1.0.8](https://www.npmjs.com/package/ag-grid-odata/v/1.0.8)
