### ISSUE TITLE
Expansion depth bigger then 2 not working

### ISSUE THREAD

**Issue by ptrushin** [SenyaMur/ag-grid-odata#8]
When I try to use column with name like 'Requirement.Customer.Name' with expansion depth bigger then 2 it is not working.
I think it is because of you use js function replace (single replace only) instead of replaceAll when you change "." to "/"
Could you repair it?

**Comment by SenyaMur** [comment]
Thanks for your issue. I fixed this bug. You can check out fix in new version [v1.0.9](https://www.npmjs.com/package/ag-grid-odata/v/1.0.9)
